In [1]:
import numpy as np

1. Исследовать на линейную зависимость:
$$f_{1}(x)=e^{x}, f_{2}(x)=1, f_{3}(x)=x+1, f_{4}(x)=x-e^{x}.$$

$f_{4}(x)=f_{3}(x)-f_{1}(x)-f_{2}(x)$, то есть вектор $f_{4}(x)$ — линейная комбинация векторов $f_{1}(x)$,$f_{2}(x)$  и $f_{3}(x)$, из чего можно сделать вывод, что представленные вектора линейно зависимы.

__2.__ Исследовать на линейную зависимость:
$$f_{1}(x)=2, f_{2}(x)=x, f_{3}(x)=x^{2}, f_{4}(x)=(x+1)^{2}=x^{2}+2x+1.$$

$f_{4}(x)=f_{3}(x)+2f_{2}(x)+f_{1}(x)*1/2$, то есть вектор $f_{4}(x)$ — линейная комбинация векторов $f_{1}(x)$,$f_{2}(x)$  и $f_{3}(x)$, из чего можно сделать вывод, что представленные вектора линейно зависимы.

__3.__ Найти координаты вектора $x = (2, 3, 5)\in \mathbb{R}^{3}$ в базисе $b_{1}=(0, 0, 10)$, $b_{2}=(2, 0, 0)$, $b_{3}=(0, 1, 0)$

In [2]:
e1 = np.array([1,0,0])
e2 = np.array([0,3,0])
e3 = np.array([0,0,9])
x = np.array([3,-2,2])

In [3]:
A = np.array([e1, e2, e3])
A_inverse = np.linalg.det(A)
A_inverse

27.0

In [4]:
e1 = np.array([0,0,10])
e2 = np.array([2,0,0])
e3 = np.array([0,1,0])
x = np.array([2,3,5])

In [5]:
A = np.array([e1, e2, e3]).transpose()
A

array([[ 0,  2,  0],
       [ 0,  0,  1],
       [10,  0,  0]])

In [6]:
A_inverse = np.linalg.inv(A)
A_inverse

array([[0. , 0. , 0.1],
       [0.5, 0. , 0. ],
       [0. , 1. , 0. ]])

In [7]:
vector = np.dot(A_inverse, x)
vector

array([0.5, 1. , 3. ])

__4.__ Найти координаты вектора $3x^{2}-2x+2\in\mathbb{R}^{3}[x]$:

а) в базисе $1$, $x$, $x^{2}$;

б) в базисе $x^{2}$, $x-1$, $1$.

In [13]:
def basis_vector(basis: list, vector: list):
    """
    -----------
    Функция, определяющая координаты вектора в заданном базисе.
    
    В качестве аргумента принимает координаты базиса и исходного вектора.
    Оба аргумента задаются в виде списка.
    -----------
    """
    e1 = np.array([basis[0], 0, 0])
    e2 = np.array([0, basis[1], 0])
    e3 = np.array([0, 0, basis[2]])
    M = np.array([e1, e2, e3])
    D_M = np.linalg.det(M)
    v1 = np.array([vector[0], vector[1], vector[2]])
    X = np.linalg.solve(M, v1)
    return X

In [9]:
X = basis_vector(basis=[1,3,9], vector=[3,-2,2])
print(f'а) Координаты вектора {round(X[0],1), round(X[1],1), round(X[2],1)}')
X = basis_vector(basis=[9,2,1], vector=[3,-2,2])
print(f'а) Координаты вектора {round(X[0],1), round(X[1],1), round(X[2],1)}')

а) Координаты вектора (3.0, -0.7, 0.2)
а) Координаты вектора (0.3, -1.0, 2.0)
