In [1]:
import numpy as np

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$



In [2]:
M1 = np.array([[1,1,-1,-2], # Матрица коэффициентов (левая часть СЛАУ)
             [2,1,-1,1],
             [1,1,-3,1]]
             )
M_ext = np.array([[1,1,-1,-2,0], # Расширенная матрица
             [2,1,-1,1,-2],
             [1,1,-3,1,4]]
             )

v1 = np.array([0,-2,4]) # Вектор (правая часть СЛАУ)

In [3]:
def isRankSimilar(a: list, b: list) -> bool:
    if np.linalg.matrix_rank(a) == np.linalg.matrix_rank(b):
        return True
    else:
        return False

In [4]:
if isRankSimilar(M1, M_ext) and np.linalg.matrix_rank(M1) != len(M1[0]):
    print('Ранги матрицы коэффициентов и расширенной матрицы равны, но при этом меньше количества неизвестных,\nследовательно система имеет бесконечное количество решений')

Ранги матрицы коэффициентов и расширенной матрицы равны, но при этом меньше количества неизвестных,
следовательно система имеет бесконечное количество решений


__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$


In [30]:
A1 = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -3, 0]])
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -3]])

if isRankSimilar(A1, A) and np.linalg.matrix_rank(A1) != len(A1[0]): 
    print(f'Система совместна и имеет единственное решение')
else:
    print(f'Система несовместна')

Система совместна и имеет единственное решение


In [31]:
B1 = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])
B = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])

if isRankSimilar(B1, B) and np.linalg.matrix_rank(B1) != len(B1[0]):
    print(f'Система совместна и имеет единственное решение')
else:
    print(f'Система несовместна')

Система несовместна


In [32]:
C1 = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])
C = np.array([[1, 2, 5], [3, 1, -8]])

if isRankSimilar(C1, C) and np.linalg.matrix_rank(C1) != len(C1[0]):
    print(f'Система совместна и имеет единственное решение')
else:
    print(f'Система несовместна')

Система совместна и имеет единственное решение


__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$



In [8]:
A1 = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4],[0, 0, 0, 2, 1]])
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0],[0, 0, 0, 2]])

if isRankSimilar(A1, A):
    print(f'Система совместна и имеет единственное решение')
else:
    print(f'Система несовместна')

Система совместна и имеет единственное решение


__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

In [28]:
# Задача решена методом подбора, range(0,3) задан для упрощения задачи поиска коэффициентов.
# В целом, учитывая результаты решения, можно сказать, что СЛАУ несовместна при условии что a, b, c неравны между собой.

M1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])


a = [x for x in range(0,3)]
b = [x for x in range(0,3)]
c = [x for x in range(0,3)]

for element_a in a:
    for element_b in b:
        for element_c in c:
#             print (element_a, element_b, element_c)
            M_with_abc = np.array([
                [1,2,3,element_a],
                [4,5,6, element_b],
                [7,8,9, element_c]
            ])
            if isRankSimilar(M1, M_with_abc) is False:
                array_abc = np.array([element_a, element_b, element_c])
                print(array_abc)
            
# isRankSimilar(M1, M_with_abc)

[0 0 1]
[0 0 2]
[0 1 0]
[0 1 1]
[0 2 0]
[0 2 1]
[0 2 2]
[1 0 0]
[1 0 1]
[1 0 2]
[1 1 0]
[1 1 2]
[1 2 0]
[1 2 1]
[1 2 2]
[2 0 0]
[2 0 1]
[2 0 2]
[2 1 1]
[2 1 2]
[2 2 0]
[2 2 1]
