In [1]:
import numpy as np

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$



In [2]:
a = np.array([[-1,-6], [2, 6]])
a

array([[-1, -6],
       [ 2,  6]])

In [4]:
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}\n')
print(f'Собственные значения:\n{w}\n')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]

Собственные значения:
[2. 3.]

Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.


<span style="color:red; font-family:Cantarell; font-size:2em;">Здесь я не смог решить задание...</span>

__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.



In [5]:
a = np.array([[1, 1], [-1, 3]])
x = np.array([[1], [1]])
z = np.dot(a, x)
z / 2

array([[1.],
       [1.]])

Так как $\lambda = 2$, следовательно вектор $x$ является собственным вектором линейного оператора $А$

__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

In [7]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
x = np.array([[3], [-3], [-4]])
z = np.dot(a, x)
z // 3

array([[-3],
       [ 3],
       [-4]])

вектор $x$ не является собственным вектором